# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=250)),
                ('v_aadhar', models.CharField(max_length=100)),
                ('v_id', models.CharField(max_length=100)),
                ('v_age', models.CharField(max_length=3)),
            ],
        ),
    ]
