# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters',
            name='id',
        ),
        migrations.AlterField(
            model_name='voters',
            name='v_aadhar',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voters',
            name='v_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voters',
            name='v_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
