# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20180314_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='v_aadhar',
            field=models.CharField(max_length=100, primary_key=True),
        ),
    ]
