# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('c_name', models.CharField(max_length=250)),
                ('c_aadhar', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('c_id', models.CharField(max_length=100, unique=True)),
                ('c_age', models.IntegerField()),
            ],
        ),
    ]
